// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBozqSCK5q1uhSDPcudjokUB3i4D_pByIA',
    appId: '1:582465997326:web:b5ad0fcef4d002b24eca5f',
    messagingSenderId: '582465997326',
    projectId: 'odadee-e78e4',
    authDomain: 'odadee-e78e4.firebaseapp.com',
    storageBucket: 'odadee-e78e4.firebasestorage.app',
    measurementId: 'G-962HRMB9DY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPpeesqML3xjmaP22n5NrN2IDAMvtiZgk',
    appId: '1:582465997326:android:d9f010b7b74224164eca5f',
    messagingSenderId: '582465997326',
    projectId: 'odadee-e78e4',
    storageBucket: 'odadee-e78e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFZB-tNKZSQOWViURFVFq8qCdsz4Hjyuw',
    appId: '1:582465997326:ios:62eee9889a8ff7164eca5f',
    messagingSenderId: '582465997326',
    projectId: 'odadee-e78e4',
    storageBucket: 'odadee-e78e4.firebasestorage.app',
    iosBundleId: 'com.odadee.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBozqSCK5q1uhSDPcudjokUB3i4D_pByIA',
    appId: '1:582465997326:web:a0f10d1f832c41364eca5f',
    messagingSenderId: '582465997326',
    projectId: 'odadee-e78e4',
    authDomain: 'odadee-e78e4.firebaseapp.com',
    storageBucket: 'odadee-e78e4.firebasestorage.app',
    measurementId: 'G-NREC15QMKL',
  );
}
